### ISSUE TITLE
Usage not clear

### ISSUE THREAD

**Issue by alliannas** [KrauseFx/danger#10]
Hi.

I'm finding it hard to understand what this actually does.
The readme says `In CI run bundle exec danger. This will look at your Dangerfile and provide some feedback based on that.`

Can you define `some feedback` in a more clearer way :)

**Comment by orta** [comment]
This project is still pretty nascent, we should definitely improve this before release.

**Comment by KrauseFx** [comment]
I'll close this for now, as I haven't even started with documentation :rocket:
