### ISSUE TITLE
Change footer text

### ISSUE THREAD

**Issue by orta** [KrauseFx/danger#23]
Instead of 

> Generated by danger on 2016-01-08

What about just: `[:no_entry_sign:anger](https://github.com/KrauseFx/danger/)` (right aligned)

The date is already on the issue, and it's cool that a bot generated the copy, but this can be snappy

<p align="right">
<a href="https://github.com/KrauseFx/danger/">:no_entry_sign:anger</a>
</p>

**Comment by KrauseFx** [comment]
Yeah :rocket:

**Comment by KrauseFx** [comment]
Not sure about :no_entry_sign:anger though, should be :no_entry_sign: danger

**Comment by KrauseFx** [comment]
Fixed :+1:

**Comment by orta** [comment]
cool cool, I'm ok with this :+1:
